### ISSUE TITLE
Feature Request: Add timer hud for spells

### ISSUE THREAD

**Issue by Zetz512** [Hedgefog/cs-halloween-mod#54]
That would be great if the wheels of fate or spells u use show you a timer hud telling you how many seconds left before it end...

Can show that below of Current Pumpkins: x hud

sry for my bad english...

cheers

**Comment by Hedgefog** [comment]
Good idea! I'll think it over!

**Comment by Hedgefog** [comment]
I've investigated this feature and tried to implement it, but many spells have no duration, and wheel of fate spells have different logic, which is why the implementation looks inconsistent and kinda weird. This implementation will confuse players, so I'll not add this to the next version.
